---

name: "Build"

on: [push, pull_request]

jobs:
  build:
    name: ${{ format('{0}', matrix.config) }}
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
    env:
      VCPKG_ROOT: ${{ format('{0}/vcpkg', github.workspace) }}
      vcpkgGitCommitId: 501db0f17ef6df184fcdbfbe0f87cde2313b6ab1
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use MSVC development command line
        uses: ilammy/msvc-dev-cmd@v1
      - name: Initialize vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
          vcpkgGitCommitId: ${{ env.vcpkgGitCommitId }}
          vcpkgJsonGlob: '**/vcpkg.json'
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ format('windows-{0}', matrix.config) }}
          buildPreset: ${{ format('windows-{0}', matrix.config) }}
