---

name: "Build"

on: [push, pull_request]

jobs:
  build:
    name: ${{ format('Build {0}-{1}', matrix.platform, matrix.config) }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [debug, release]
        include:
          - os: ubuntu-latest
            platform: linux
            triplet: x64-linux
          - os: windows-latest
            platform: windows
            triplet: x64-windows-static
    env:
      pkgs: fmt jsoncpp spdlog
      VCPKG_ROOT: ${{ format('{0}/vcpkg', github.workspace) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use MSVC CLI
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.platform == 'windows' }}
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Initialize vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          pkgs: ${{ env.pkgs }}
          triplet: ${{ matrix.triplet }}
          token: ${{ github.token }}
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ format('{0}-{1}', matrix.platform, matrix.config) }}
          buildPreset: ${{ format('{0}-{1}', matrix.platform, matrix.config) }}
