---

name: "Build"

on: [push, pull_request]

jobs:
  build:
    name: ${{ format('{0}', matrix.config) }}
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
    env:
      pkgs: argparse dlib fmt jsoncpp opencv spdlog
      VCPKG_ROOT: ${{ format('{0}/vcpkg', github.workspace) }}
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use MSVC development command line
        uses: ilammy/msvc-dev-cmd@v1
      - name: Download model
        run: |
          curl -O https://raw.githubusercontent.com/fenollp/data.shape_predictor_68_face_landmarks/main/shape_predictor_68_face_landmarks.dat
      - name: Initialize vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          pkgs: ${{ env.pkgs }}
          triplet: x64-windows-static
          token: ${{ github.token }}
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ format('windows-{0}', matrix.config) }}
          buildPreset: ${{ format('windows-{0}', matrix.config) }}
